# Generated by Django 5.2.14 on 2026-06-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
